var fs = require('fs');

var Sprite = require("../index.js").Sprite;
var sprite = new Sprite();
sprite.addImageSrc([
  "./img/objectType/account.png",
  "./img/objectType/answer.png",
  "./img/objectType/attachment.png",
  "./img/objectType/board.png",
  "./img/objectType/campaign.png",
  "./img/objectType/case.png",
  "./img/objectType/category.png",
  "./img/objectType/comment.png",
  "./img/objectType/contact.png",
  "./img/objectType/contract.png",
  "./img/objectType/event.png",
  "./img/objectType/file.png",
  "./img/objectType/kb.png",
  "./img/objectType/lead.png",
  "./img/objectType/message.png",
  "./img/objectType/note.png",
  "./img/objectType/opportunity.png",
  "./img/objectType/partner.png",
  "./img/objectType/product.png",
  "./img/objectType/rss.png",
  "./img/objectType/task.png",
  "./img/objectType/thread.png",
  "./img/objectType/user.png",
  "./img/common/amount.png",
  "./img/common/checkbox_active.png",
  "./img/common/checkbox_inactive.png",
  "./img/common/clear-mobile.png",
  "./img/common/clear.png",
  "./img/common/copy.png",
  "./img/common/coveo-cloud.png",
  "./img/common/coveo.png",
  "./img/common/datepicker.png",
  "./img/common/delete.png",
  "./img/common/doritos.png",
  "./img/common/get_started.png",
  "./img/common/lock.png",
  "./img/common/login_user.png",
  "./img/common/logo_light_large.png",
  "./img/common/logo_light.png",
  "./img/common/menu_reauthenticate.png",
  "./img/common/menu_shareresult.png",
  "./img/common/poweredbycoveo.png",
  "./img/common/settings.png",
  "./img/common/small_x.png",
  "./img/common/star_active.png",
  "./img/common/star_inactive.png",
  "./img/common/star_placeholder.png",
  "./img/common/system.png",
  "./img/common/tagging_ok.png",
  "./img/common/tagging_tag.png",
  "./img/common/tagging-cancel_clear.png",
  "./img/common/tagging-cancel_delete.png",
  "./img/common/thumbdown_active.png",
  "./img/common/thumbdown_inactive.png",
  "./img/common/thumbup_active.png",
  "./img/common/thumbup_inactive.png"
], function(){
  var obj = sprite.compile('./sprite.png');
  obj.png.pipe(fs.createWriteStream('sprite.png'));
  fs.writeFile('sprite.css', obj.css);
});